name: Ansible lint/test with Makefile

on:
  workflow_call:
    secrets:
      SSH_PRIV_KEY:
        required: false

jobs:
  ansible-test:
    name: Ansible lint/test
    runs-on: ubuntu-latest
    env:
      PY_COLORS: '1'
      ANSIBLE_FORCE_COLOR: '1'
      DISABLE_VENV: '1' # disable venv on Makefile
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import private key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIV_KEY }}
        if: secrets.SSH_PRIV_KEY != null

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          pip install -q -U pip setuptools wheel
          pip install -q PyYAML
          make configure env-dump

      - name: Lint code
        run: |
          make lint

      - name: Run tests
        run: |
          make test

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
        if: failure()
